// AUTO-GENERATED by scripts/generate-shard-configs.mjs. Do not edit by hand.
//
// The routing table the shard router matches against. It is written from `server-shards.json` after
// the OpenNext build — the plan is derived from Next's own route traces, so it cannot live in the
// repository. The committed copy is an empty placeholder so the app type-checks on a fresh clone; CI
// regenerates this file before the router is built and deployed.

export interface ShardRoute {
  /** The service binding on the router that points at the shard owning this route. */
  binding: string;
  /** An anchored regular expression source matching the route's URL path. */
  source: string;
}

/** Routes, ordered most-specific first. */
export const shardRoutes: ShardRoute[] = [];

/** Next's internal rewrites, mapped to the shard that owns the rewrite's destination. */
export const shardAliases: ShardRoute[] = [];

/** Used when no route matches: Next's own redirects, rewrites, the 404 boundary and image requests. */
export const fallbackBinding = "SHARD_1";
